name: Fossology check
on: [pull_request, push]

permissions:
  contents: read

jobs:
  check-license:
    name: Check license, copyright, keyword
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - run: |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_ACTIONS=true \
            fossology/fossology:scanner "/bin/fossologyscanner" --report TEXT repo nomos ojo copyright keyword
      # Upload artifact
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: scan-fossology-report
          path: ./results

      # Artifact download
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
         name: scan-fossology-report
