name: Pull Request Labeler

on:
  schedule:
    - cron: "*/5 * * * *"
 
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3-preview
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
