name: License Finder
on: [push, pull_request]

permissions:
  contents: read

jobs:
  license_finder:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/license_finder

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: License finder run
        run: | 
          license_finder approvals add awesome_gpl_gem
          license_finder > ./license-finder-report

      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: scan-license-finder-report
          path: ./license-finder-report

      - name: Artifact download
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          name: scan-license-finder-report
