name: License Finder
on: [push, pull_request]

permissions:
  contents: read

jobs:
  license_finder:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/license_finder

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: License finder run
        run: | 
          license_finder approvals add awesome_gpl_gem
          license_finder > ./license-finder-report

      - name: Upload artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: scan-license-finder-report
          path: ./license-finder-report

      - name: Artifact download
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: scan-license-finder-report
