name: License Finder
on: [push, pull_request]

permissions:
  contents: read

jobs:
  license_finder:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/license_finder

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: License finder run
        run: | 
          license_finder approvals add awesome_gpl_gem
          license_finder > ./license-finder-report

      - name: Upload artifact
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
        with:
          name: scan-license-finder-report
          path: ./license-finder-report

      - name: Artifact download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: scan-license-finder-report
