name: License Finder
on: [push, pull_request]

permissions:
  contents: read

jobs:
  license_finder:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/license_finder

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: License finder run
        run: | 
          license_finder approvals add awesome_gpl_gem
          license_finder > ./license-finder-report

      - name: Upload artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: scan-license-finder-report
          path: ./license-finder-report

      - name: Artifact download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: scan-license-finder-report
