name: cpp-linter

on: [push, pull_request]

permissions:
  contents: read

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: cpp-linter/cpp-linter-action@08d1ce7079c971911b36673d2818aef029de8a2e  
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''
          files-changed-only: false
          ignore: crypto

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
        # for actual deployment
        # run: exit 1
