---
name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install extra tools
        run: |
          sudo apt-get install -y git gcc subversion make gperf flex bison libncurses5-dev texinfo g++ curl pkg-config  autoconf libtool libtool-bin gcc-multilib doxygen doxygen-gui libssl-dev libcurl4-openssl-dev wget

      - name: Build the project
        run: |
          make PLATFORM=numaker_pfm_m2351 create_context
          svn --force export https://github.com/OpenNuvoton/M2351BSP/trunk/Library/Device/Nuvoton/M2351/Source/GCC/_syscalls.c ./arch/cortex-m23/m2351/src/Device/Nuvoton/M2351/Source/GCC/_syscalls.c
          svn --force export https://github.com/OpenNuvoton/M2351BSP/trunk/SampleCode/MKROM/SecureBootDemo/NuBL2/main.c ./arch/cortex-m23/m2351/src/NuBL2/
          svn --force export https://github.com/OpenNuvoton/M2351BSP/trunk/SampleCode/MKROM/SecureBootDemo/NuBL2/VerifyNuBL3x.c ./arch/cortex-m23/m2351/src/NuBL2/
          svn --force export https://github.com/OpenNuvoton/M2351BSP/trunk/SampleCode/MKROM/SecureBootDemo/NuBL2/NuBL2.h ./arch/cortex-m23/m2351/src/NuBL2/
          svn --force export https://github.com/OpenNuvoton/M2351BSP/trunk/SampleCode/MKROM/SecureBootDemo/NuBL2/FwInfo/FwInfo.c ./arch/cortex-m23/m2351/src/NuBL2
          make toolchain
          make
