name: Scancode
on: [push, pull_request]

permissions:
  contents: read

jobs:
  scancode:
    runs-on: ubuntu-latest

    container:
      image: gianlucadb0/scancode-toolkit

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Create results directory
        run: mkdir results

      - name: Scancode run
        run: scancode -clpeui -n 2 --cyclonedx ./results/sbom-cyclonedx --spdx-rdf ./results/sbom-spdx ./

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: scan-scancode-report
          path: ./results/

      - name: Artifact download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: scan-scancode-report